node {
   def commit_id
   stage('step pre') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'fd27ddfc-b47b-42cc-8db1-2ad1d9cfdb8d') {
       def app = docker.build("fd27ddfc-b47b-42cc-8db1-2ad1d9cfdb8d/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
     sh label: '', script: '''docker rm docker_test
      docker run --rm -tid --name docker_test -p 3000 fd27ddfc-b47b-42cc-8db1-2ad1d9cfdb8d/docker-nodejs-demo:latest
      docker kill docker_test
      
      '''
     }
   }

