node {
   def commit_id
   def docker_login = 'nirrea839'
   def docker_image = 'nirrea839/docker-nodejs-demo'
   stage('step pre') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', "${docker_login}") {
       def app = docker.build("${docker_image}:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
      
      sh "docker run --rm -tid --name docker_test -p 3000 ${docker_image}:${commit_id}"
      sh 'docker kill docker_test'
      
     }
   }
